remote_theme: pages-themes/minimal@v0.2.0
title: [Ahmed Uluca]
description: [Experimenting..]
show_downloads: ["false"]
google_analytics: ["G-58PEL0F91D"]
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
